#!/bin/bash

set -e

export DEVTOOLS_DIRECTORY="$HOME/.devtools"

# automatically update application if enabled
if [ -f "$DEVTOOLS_DIRECTORY/.autoupdate" ]; then
    # shellcheck disable=SC1090
    source "$DEVTOOLS_DIRECTORY/bin/self/update.sh"
fi

# command file
EXECUTE_FILE="$DEVTOOLS_DIRECTORY/bin/$1/$2.sh"

# execute command
if [ -f "$EXECUTE_FILE" ]; then
  # shellcheck disable=SC1090
  source "$EXECUTE_FILE"
else
  echo "devtools: command not found!"
  echo ""
  echo "domain:"
  echo " devtools domain add <domain>"
  echo " devtools domain disable <domain>"
  echo " devtools domain delete <domain>"
  echo ""
  echo "setup:"
  echo " devtools setup nginx"
  echo ""
  echo "self:"
  echo " devtools self update"
  echo " devtools self autoupdate"
fi
