#!/bin/bash

set -e

export DEVTOOLS_DIRECTORY="$HOME/.devtools"

EXECUTE_FILE="$DEVTOOLS_DIRECTORY/bin/$1/$2.sh"

# execute command
if [ -f "$EXECUTE_FILE" ]; then
  # shellcheck disable=SC1090
  source "$EXECUTE_FILE"
else
  echo "devtools: command not found!"
  echo ""
  echo "devtools domain add <domain>"
  echo "devtools setup nginx"
  echo "devtools tools update"
fi
